### ISSUE TITLE
UserWarning: The module databroker.core is just a shim for backward-compatibility. You can import directly from databroker.   warn("The module databroker.core is just a shim for backward-compatibility. "

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-ESM/profile_collection#3]
```python
xf21id1@xf21id1-ws1:~$ bsui 
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: collection
Loading metadata history from /home/xf21id1/.config/bluesky/bluesky_history.db
/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/databroker/core.py:3: UserWarning: The module databroker.core is just a shim for backward-compatibility. You can import directly from databroker.
  warn("The module databroker.core is just a shim for backward-compatibility. "
/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/suspenders.py:505: UserWarning: bluesky.suspenders.SuspendOutBand is deprecated.
  warn("bluesky.suspenders.SuspendOutBand is deprecated.")

In [1]: 
```

**Comment by mrakitin** [comment]
Attn @tacaswell, @danielballan

**Comment by danielballan** [comment]
Something somewhere must be importing from `databroker.core`, but I can't find that in this repo or in esmtools. This is not related to `bluesky_history.db`, btw; the messages just happen to be coming out consecutively.

**Comment by awalter-bnl** [comment]
I am not sure where this is occurring, however he Github master repo and the copies on each computer are all the same. In addition we get the same error on both computers so it must be in there somewhere !-)

cheers
Andrew


Andrew Walter
Assc. Scientist
NSLS II, Photon sciences directorate
Brookhaven National Laboratory
Building 741, Rm 108
Upton New York, USA, 11973
Email: awalter@bnl.gov<mailto:awalter@bnl.gov>
Phone:
office: 631 344 4055
        beamline: 631 374 1621



On Jan 19, 2018, at 1:51 PM, Dan Allan <notifications@github.com<mailto:notifications@github.com>> wrote:


Something somewhere must be importing from databroker.core, but I can't find that in this repo or in esmtools. This is not related to bluesky_history.db, btw; the messages just happen to be coming out consecutively.

**Comment by mrakitin** [comment]
The issue is not observed anymore with `collection-2019-2.0-esm` env on xf21id1-ws2.
